### ISSUE TITLE
Visual Studio MAC

### ISSUE THREAD

**Issue by aiaaaa** [Burnett01/pxd-to-wav#2]
I attempted to open this file in Visual Studio for MAC. Is this something that is possible or will I need to get access to PC or run a virtual machine?

Thanks for this content, looking forward to backing  up eJay Rave samples.

**Comment by Burnett01** [comment]
Hello @aiaaaa I don't think this will work on a unix-like OS such as MacOS. On Linux, maybe wine could run the DLL. I will look into it

**Comment by Burnett01** [comment]
As stated earlier, this won't be possible without further adjustments in terms of running the ejay dlls on linux with Wine or other toolchains.
